//! Snotice rule CRUD + pattern tester.
//!
//! Rules live in `ClientState.snotice_rules` (Arc<Mutex<Vec<CompiledSnoticeRule>>>).
//! The dispatcher (M4) already reads from this store at runtime; M6 fills in
//! the management API and on-disk persistence under
//! `~/Library/Application Support/FlumeMac/snotice.toml`.

use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};

use crate::dispatch::CompiledSnoticeRule;
use crate::{error::FlumeError, paths, FlumeClient};

#[derive(Debug, Clone, uniffi::Record, Serialize, Deserialize)]
pub struct SnoticeRule {
    /// Stable identifier. Generated by `add_snotice_rule` if empty; preserved
    /// across save/load so the UI can hold long-lived references.
    pub id: String,
    /// Regex pattern matched against the notice text.
    pub pattern: String,
    /// Optional `${1}`-style format applied to the matched text.
    pub format: Option<String>,
    /// Optional destination buffer name. Empty/None routes nowhere visible.
    pub buffer: Option<String>,
    /// If true, the notice is dropped instead of routed.
    pub suppress: bool,
    /// If false, the rule is kept in the list but skipped at match time.
    pub enabled: bool,
}

// ───────────────────────── persistence wire format ─────────────────────────

#[derive(Serialize, Deserialize, Default)]
struct SnoticeFile {
    #[serde(default, rename = "rule")]
    rules: Vec<SnoticeRule>,
}

pub(crate) fn load_persisted_rules(
    path: &std::path::Path,
) -> Result<Vec<SnoticeRule>, FlumeError> {
    if !path.exists() {
        return Ok(Vec::new());
    }
    let contents = std::fs::read_to_string(path)
        .map_err(|e| FlumeError::Config(format!("read {}: {}", path.display(), e)))?;
    let file: SnoticeFile = toml::from_str(&contents)
        .map_err(|e| FlumeError::Config(format!("parse {}: {}", path.display(), e)))?;
    Ok(file.rules)
}

fn save_persisted_rules(
    path: &std::path::Path,
    rules: &[SnoticeRule],
) -> Result<(), FlumeError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| FlumeError::Config(format!("mkdir {}: {}", parent.display(), e)))?;
    }
    let toml_str = toml::to_string_pretty(&SnoticeFile {
        rules: rules.to_vec(),
    })
    .map_err(|e| FlumeError::Config(format!("serialize: {}", e)))?;
    std::fs::write(path, toml_str)
        .map_err(|e| FlumeError::Config(format!("write {}: {}", path.display(), e)))?;
    Ok(())
}

// ───────────────────────── compile / view conversion ─────────────────────────

pub(crate) fn compile_rule(rule: &SnoticeRule) -> Result<CompiledSnoticeRule, FlumeError> {
    let regex = regex::Regex::new(&rule.pattern)
        .map_err(|e| FlumeError::InvalidArgument(format!("invalid regex: {}", e)))?;
    Ok(CompiledSnoticeRule {
        id: rule.id.clone(),
        pattern: rule.pattern.clone(),
        regex,
        format: rule.format.clone(),
        buffer: rule.buffer.clone(),
        suppress: rule.suppress,
        enabled: rule.enabled,
    })
}

fn view(c: &CompiledSnoticeRule) -> SnoticeRule {
    SnoticeRule {
        id: c.id.clone(),
        pattern: c.pattern.clone(),
        format: c.format.clone(),
        buffer: c.buffer.clone(),
        suppress: c.suppress,
        enabled: c.enabled,
    }
}

fn new_id() -> String {
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let micros = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_micros() as u64)
        .unwrap_or(0);
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("{:x}-{:x}", micros, n)
}

// ───────────────────────── FFI surface ─────────────────────────

#[uniffi::export]
impl FlumeClient {
    pub fn list_snotice_rules(&self) -> Vec<SnoticeRule> {
        let state = self.state.lock().expect("state poisoned");
        let rules = state.snotice_rules.lock().expect("rules poisoned");
        rules.iter().map(view).collect()
    }

    /// Append a rule. If `rule.id` is empty, a fresh id is generated and
    /// returned in the stored copy (call `list_snotice_rules()` to fetch).
    /// Validates the regex via `regex::Regex::new`.
    pub fn add_snotice_rule(&self, mut rule: SnoticeRule) -> Result<(), FlumeError> {
        if rule.pattern.is_empty() {
            return Err(FlumeError::InvalidArgument("pattern is empty".into()));
        }
        if rule.id.is_empty() {
            rule.id = new_id();
        }
        let compiled = compile_rule(&rule)?;
        let state = self.state.lock().expect("state poisoned");
        let mut rules = state.snotice_rules.lock().expect("rules poisoned");
        if rules.iter().any(|r| r.id == compiled.id) {
            return Err(FlumeError::InvalidArgument(format!(
                "rule id '{}' already exists",
                compiled.id
            )));
        }
        rules.push(compiled);
        Ok(())
    }

    pub fn remove_snotice_rule(&self, id: String) {
        let state = self.state.lock().expect("state poisoned");
        let mut rules = state.snotice_rules.lock().expect("rules poisoned");
        rules.retain(|r| r.id != id);
    }

    /// Replace the rule with the same id. Errors if no rule matches or the
    /// new pattern fails to compile.
    pub fn update_snotice_rule(&self, rule: SnoticeRule) -> Result<(), FlumeError> {
        if rule.id.is_empty() {
            return Err(FlumeError::InvalidArgument("id is empty".into()));
        }
        let compiled = compile_rule(&rule)?;
        let state = self.state.lock().expect("state poisoned");
        let mut rules = state.snotice_rules.lock().expect("rules poisoned");
        let Some(slot) = rules.iter_mut().find(|r| r.id == compiled.id) else {
            return Err(FlumeError::InvalidArgument(format!(
                "no rule with id '{}'",
                compiled.id
            )));
        };
        *slot = compiled;
        Ok(())
    }

    /// Flush the in-memory rule list to
    /// `~/Library/Application Support/FlumeMac/snotice.toml`.
    pub fn save_snotice_rules(&self) -> Result<(), FlumeError> {
        let path = paths::snotice_config_path().ok_or_else(|| {
            FlumeError::Config("could not resolve snotice.toml path ($HOME unset?)".into())
        })?;
        let rules: Vec<SnoticeRule> = {
            let state = self.state.lock().expect("state poisoned");
            let rules = state.snotice_rules.lock().expect("rules poisoned");
            rules.iter().map(view).collect()
        };
        save_persisted_rules(&path, &rules)
    }

    /// Compile `pattern` and run it against `text`. Returns the capture
    /// groups (group 0 = full match, then 1..) — empty if there's no match.
    /// Powers the visual rule-editor preview.
    pub fn test_snotice_pattern(
        &self,
        pattern: String,
        text: String,
    ) -> Result<Vec<String>, FlumeError> {
        let re = regex::Regex::new(&pattern)
            .map_err(|e| FlumeError::InvalidArgument(format!("invalid regex: {}", e)))?;
        let Some(caps) = re.captures(&text) else {
            return Ok(Vec::new());
        };
        Ok(caps
            .iter()
            .map(|m| m.map(|m| m.as_str().to_string()).unwrap_or_default())
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serial_test::serial;
    use tempfile::TempDir;

    fn fresh_client() -> std::sync::Arc<FlumeClient> {
        let tmp = TempDir::new().unwrap();
        std::env::set_var("FLUME_MAC_CONFIG_DIR", tmp.path());
        let c = FlumeClient::new();
        std::mem::forget(tmp);
        c
    }

    fn rule(pattern: &str, buffer: Option<&str>) -> SnoticeRule {
        SnoticeRule {
            id: String::new(),
            pattern: pattern.into(),
            format: None,
            buffer: buffer.map(String::from),
            suppress: false,
            enabled: true,
        }
    }

    #[test]
    #[serial]
    fn add_assigns_id_and_appears_in_list() {
        let client = fresh_client();
        client.add_snotice_rule(rule(r"Client connecting", Some("snotice-conn"))).unwrap();
        let listed = client.list_snotice_rules();
        assert_eq!(listed.len(), 1);
        assert!(!listed[0].id.is_empty(), "id should be auto-generated");
        assert_eq!(listed[0].pattern, "Client connecting");
    }

    #[test]
    #[serial]
    fn add_rejects_invalid_regex() {
        let client = fresh_client();
        let err = client.add_snotice_rule(rule(r"(unclosed", None)).unwrap_err();
        assert!(matches!(err, FlumeError::InvalidArgument(_)));
    }

    #[test]
    #[serial]
    fn add_rejects_duplicate_explicit_id() {
        let client = fresh_client();
        let mut r1 = rule(r".*", None);
        r1.id = "fixed".into();
        client.add_snotice_rule(r1).unwrap();
        let mut r2 = rule(r"other", None);
        r2.id = "fixed".into();
        let err = client.add_snotice_rule(r2).unwrap_err();
        assert!(matches!(err, FlumeError::InvalidArgument(_)));
    }

    #[test]
    #[serial]
    fn remove_by_id() {
        let client = fresh_client();
        client.add_snotice_rule(rule(r"a", None)).unwrap();
        client.add_snotice_rule(rule(r"b", None)).unwrap();
        let ids: Vec<String> = client
            .list_snotice_rules()
            .into_iter()
            .map(|r| r.id)
            .collect();
        client.remove_snotice_rule(ids[0].clone());
        let after = client.list_snotice_rules();
        assert_eq!(after.len(), 1);
        assert_eq!(after[0].id, ids[1]);
    }

    #[test]
    #[serial]
    fn update_replaces_existing() {
        let client = fresh_client();
        client.add_snotice_rule(rule(r"old", None)).unwrap();
        let mut existing = client.list_snotice_rules().pop().unwrap();
        existing.pattern = "new".into();
        existing.suppress = true;
        client.update_snotice_rule(existing.clone()).unwrap();
        let after = client.list_snotice_rules().pop().unwrap();
        assert_eq!(after.pattern, "new");
        assert!(after.suppress);
    }

    #[test]
    #[serial]
    fn update_unknown_id_errors() {
        let client = fresh_client();
        let mut r = rule(r"x", None);
        r.id = "ghost".into();
        let err = client.update_snotice_rule(r).unwrap_err();
        assert!(matches!(err, FlumeError::InvalidArgument(_)));
    }

    #[test]
    #[serial]
    fn save_and_reload_roundtrip() {
        let tmp = TempDir::new().unwrap();
        std::env::set_var("FLUME_MAC_CONFIG_DIR", tmp.path());

        let c1 = FlumeClient::new();
        c1.add_snotice_rule(SnoticeRule {
            id: String::new(),
            pattern: r"Client connecting: (\S+)".into(),
            format: Some("[connect] ${1}".into()),
            buffer: Some("snotice-conn".into()),
            suppress: false,
            enabled: true,
        })
        .unwrap();
        c1.add_snotice_rule(SnoticeRule {
            id: String::new(),
            pattern: r"Oper-up".into(),
            format: None,
            buffer: None,
            suppress: true,
            enabled: false,
        })
        .unwrap();
        c1.save_snotice_rules().unwrap();

        // Fresh client loads from disk.
        std::env::set_var("FLUME_MAC_CONFIG_DIR", tmp.path());
        let c2 = FlumeClient::new();
        let listed = c2.list_snotice_rules();
        assert_eq!(listed.len(), 2);
        let connect = listed.iter().find(|r| r.pattern.contains("connecting")).unwrap();
        assert_eq!(connect.format.as_deref(), Some("[connect] ${1}"));
        assert_eq!(connect.buffer.as_deref(), Some("snotice-conn"));
        assert!(connect.enabled);
        let oper = listed.iter().find(|r| r.pattern == "Oper-up").unwrap();
        assert!(oper.suppress);
        assert!(!oper.enabled);
    }

    #[test]
    #[serial]
    fn test_pattern_returns_capture_groups() {
        let client = fresh_client();
        let groups = client
            .test_snotice_pattern(
                r"Client connecting: (\S+) on (\S+)".into(),
                "Client connecting: alice on lithium.libera.chat".into(),
            )
            .unwrap();
        assert_eq!(groups.len(), 3);
        assert_eq!(groups[0], "Client connecting: alice on lithium.libera.chat");
        assert_eq!(groups[1], "alice");
        assert_eq!(groups[2], "lithium.libera.chat");
    }

    #[test]
    #[serial]
    fn test_pattern_no_match_is_empty() {
        let client = fresh_client();
        let groups = client
            .test_snotice_pattern(r"^never$".into(), "matches nothing".into())
            .unwrap();
        assert!(groups.is_empty());
    }

    #[test]
    #[serial]
    fn test_pattern_invalid_regex_errors() {
        let client = fresh_client();
        let err = client
            .test_snotice_pattern(r"(unclosed".into(), "x".into())
            .unwrap_err();
        assert!(matches!(err, FlumeError::InvalidArgument(_)));
    }

    #[test]
    #[serial]
    fn disabled_rule_is_skipped_by_dispatcher() {
        // End-to-end: a disabled rule with a buffer name should NOT create
        // the buffer when a matching notice arrives.
        use crate::dispatch::ServerDispatcher;
        use crate::buffers::ServerBuffers;
        use crate::servers::{ConnectionState, ServerSnapshot};
        use std::sync::{Arc, Mutex};

        let client = fresh_client();
        client
            .add_snotice_rule(SnoticeRule {
                id: String::new(),
                pattern: r"hello".into(),
                format: None,
                buffer: Some("snotice-x".into()),
                suppress: false,
                enabled: false,
            })
            .unwrap();
        let snotice_rules = {
            let state = client.state.lock().unwrap();
            Arc::clone(&state.snotice_rules)
        };

        let d = ServerDispatcher {
            server_name: "libera".into(),
            snapshot: Arc::new(Mutex::new(ServerSnapshot {
                state: ConnectionState::Connected,
                our_nick: Some("me".into()),
                user_modes: String::new(),
                capabilities: Vec::new(),
            })),
            buffers: Arc::new(Mutex::new(ServerBuffers::default())),
            snotice_rules,
        };

        // A server-style notice that matches the disabled rule's pattern.
        use flume_core::event::IrcEvent;
        use flume_core::irc::command::{Command, ParsedMessage};
        use flume_core::irc::message::OwnedPrefix;
        let events = d.handle(IrcEvent::MessageReceived {
            server_name: "libera".into(),
            message: ParsedMessage {
                tags: Vec::new(),
                prefix: Some(OwnedPrefix::Server("libera.chat".into())),
                command: Command::Notice {
                    target: "*".into(),
                    text: "say hello there".into(),
                },
                server_time: None,
            },
        });
        // Falls through routing → becomes a regular Notice event, not SnoticeRouted.
        assert!(matches!(events[0], crate::events::Event::Notice { .. }));
        assert!(d.buffers.lock().unwrap().map.is_empty());
    }
}
